<?php

namespace App\Agents;

use App\DTOs\ReviewerContextDTO;
use App\DTOs\ReviewResultDTO;
use App\Models\Incident;
use App\Services\MCP\ClaudeReActEngine;
use App\Services\MCP\GeminiReActEngine;
use App\Services\MCP\MCPToolGateway;
use App\Services\Verification\DiffAuditorService;
use App\Services\Verification\PoCMitigationVerifier;
use App\Services\Verification\RegressionTestRunner;
use App\Tools\Enums\AgentRole;

class ReviewerAgent
{
    /**
     * System prompt defining adversarial review mandates and strict read-only constraints.
     */
    public const SYSTEM_PROMPT = <<<'PROMPT'
You are the Reviewer Agent in PatchOps, an autonomous security remediation system.

YOUR ROLE:
You are an independent, adversarial security auditor and verification engineer. You receive candidate patches generated by the Patch Synthesizer. You DO NOT trust the patch candidate. Your mandate is to ruthlessly verify whether the patch mitigates the reported vulnerability without breaking existing functionality or introducing security regressions.

STRICT OPERATIONAL CONSTRAINTS:
1. READ-ONLY EVALUATION: You must NEVER write, modify, or rewrite code or patch files. You evaluate what was delivered as-is.
2. INDEPENDENT VERIFICATION: You must run both the original reproduction proof-of-concept (to verify mitigation) AND the full regression test suite (to verify safety).
3. EMPIRICAL EVIDENCE: Never guess or assume a test passes. Every assertion in your verdict must be backed by exit codes, stdout/stderr streams, and sandbox command logs.

INPUT CONTEXT YOU RECEIVE:
- Patch Candidate: Unified diff / patch file produced by the Patch Synthesizer.
- Original Vulnerability: CVE identifier, advisory details, and root cause analysis.
- Reproduction Evidence: The initial proof-of-concept command, expected vulnerable output, and reproduction trace.
- Repository Context: Ecosystem manifests (package.json, composer.json, etc.), runtime versions, and commit SHA.
- Regression Test Suites: Existing unit, integration, and security test commands.

EVALUATION PROTOCOL:
Follow this deterministic sequence inside your isolated sandbox:
1. Inspect Patch: Audit the diff for suspicious patterns, crude workarounds, disabled tests, hardcoded bypasses, or commented-out security guards.
2. Apply Candidate: Apply the unified diff onto the pinned repository state.
3. Verify Vulnerability Mitigation: Run the exact reproduction command / PoC script that proved the issue earlier.
   - EXPECTED: The exploit MUST FAIL to execute or be properly handled (e.g., return 401/403/validation error instead of code execution).
4. Run Regression Tests: Execute existing project test suites (e.g., `npm test`, `pytest`, `composer test`, `go test ./...`).
   - EXPECTED: All pre-existing test suites must pass (exit code 0).
5. Run Build & Typecheck: Run project build or compile steps (e.g., `npm run build`, `tsc --noEmit`).
   - EXPECTED: Zero compilation or bundling errors.
6. Run Security Checks: Verify that the patch does not introduce new common weaknesses (e.g., shell injection, unescaped queries, permissive CORS).
7. Synthesize Verdict: Compile findings into the required structured schema.

IF ANY STEP FAILS:
Do NOT attempt to fix it yourself. Immediately terminate verification, document the exact failure output, and return a structured verdict with `approved: false`.

OUTPUT SCHEMA:
At the conclusion of your evaluation, you must invoke the `record_review_verdict` terminal tool.
PROMPT;

    public function __construct(
        protected ?MCPToolGateway $gateway = null,
        protected ?ClaudeReActEngine $reactEngine = null,
        protected ?DiffAuditorService $diffAuditor = null,
        protected ?PoCMitigationVerifier $pocVerifier = null,
        protected ?RegressionTestRunner $testRunner = null,
        protected ?GeminiReActEngine $geminiEngine = null,
    ) {
        $this->gateway ??= app(MCPToolGateway::class);
        $this->reactEngine ??= app(ClaudeReActEngine::class);
        $this->diffAuditor ??= app(DiffAuditorService::class);
        $this->pocVerifier ??= app(PoCMitigationVerifier::class);
        $this->testRunner ??= app(RegressionTestRunner::class);
        $this->geminiEngine ??= app(GeminiReActEngine::class);
    }

    /**
     * Execute the multi-tiered verification pipeline for a candidate patch.
     */
    public function execute(ReviewerContextDTO $context): ReviewResultDTO
    {
        $incident = $this->resolveIncident($context);

        // STAGE 1: Deterministic static diff audit (pre-LLM and pre-sandbox)
        $diffAudit = $this->diffAuditor->audit($context->patchCandidateDiff);
        if (! $diffAudit->passed) {
            return ReviewResultDTO::rejected(
                reason: 'Patch candidate failed deterministic safety audit.',
                details: $diffAudit->violations,
                metadata: ['stage' => 'stage_1_diff_audit'],
            );
        }

        // STAGE 2: Adversarial PoC mitigation verification
        $pocCommand = $context->reproductionEvidence['command'] ?? null;
        if (! empty($pocCommand) && ! empty($context->sandboxId)) {
            $pocCheck = $this->pocVerifier->verifyMitigation(
                incident: $incident,
                sandboxId: $context->sandboxId,
                pocCommand: $pocCommand,
                agentRunId: $context->agentRunId,
            );

            if (! $pocCheck['mitigated']) {
                $detail = ! empty($pocCheck['stdout']) ? $pocCheck['stdout'] : ($pocCheck['stderr'] ?: 'Exploit signature still active after patch.');

                return ReviewResultDTO::rejected(
                    reason: 'Original vulnerability is still exploitable after patch.',
                    details: [$detail],
                    metadata: ['stage' => 'stage_2_poc_mitigation', 'poc_result' => $pocCheck],
                    vulnerabilityMitigated: false,
                );
            }
        }

        // STAGE 3: Multi-tiered regression and safety test enforcement
        $hasRegressionTests = ! empty($context->regressionTestCommand) || ! empty($context->testSuites);
        if ($hasRegressionTests && ! empty($context->sandboxId)) {
            $regressionResult = $this->testRunner->runTests(
                incident: $incident,
                sandboxId: $context->sandboxId,
                regressionCommand: $context->regressionTestCommand,
                testSuites: $context->testSuites,
                agentRunId: $context->agentRunId,
            );

            if (! $regressionResult['passed']) {
                return ReviewResultDTO::rejected(
                    reason: 'Generated regression test failed to pass against candidate patch.',
                    details: $regressionResult['failed_tests'],
                    metadata: ['stage' => 'stage_3_regression_tests', 'checks' => $regressionResult['checks']],
                    vulnerabilityMitigated: true,
                    buildPassed: false,
                    checks: $regressionResult['checks'],
                );
            }
        }

        // STAGE 4: ReAct agent verification & verdict synthesis
        $systemPrompt = $this->buildSystemPrompt();

        // Read-only + sandbox lifecycle tools only
        $availableTools = [
            'sandbox.create',
            'sandbox.clone',
            'sandbox.install',
            'sandbox.execute',
            'sandbox.logs',
            'sandbox.destroy',
            'workspace.read_file',
            'workspace.list_files',
            'record_review_verdict', // Terminal tool
        ];

        if (config('services.gemini.api_key') || ! config('services.anthropic.key')) {
            $verdictData = $this->geminiEngine->run(
                role: AgentRole::REVIEWER,
                systemInstruction: $systemPrompt,
                context: $context->toArray(),
                tools: $availableTools,
                maxIterations: 12,
                incident: $incident,
                agentRunId: $context->agentRunId ? (int) $context->agentRunId : null,
            );

            return ReviewResultDTO::fromArray($verdictData);
        }

        return $this->reactEngine->run(
            role: AgentRole::REVIEWER,
            systemPrompt: $systemPrompt,
            context: $context->toArray(),
            tools: $availableTools,
            maxIterations: 12,
            incident: $incident,
            agentRunId: $context->agentRunId ? (int) $context->agentRunId : null,
        );
    }

    /**
     * Build the adversarial system prompt.
     */
    protected function buildSystemPrompt(): string
    {
        return self::SYSTEM_PROMPT;
    }

    /**
     * Resolve incident from context.
     */
    protected function resolveIncident(ReviewerContextDTO $context): Incident
    {
        return Incident::firstOrNew([
            'incident_number' => $context->incidentId,
        ], [
            'title' => "Security Audit: {$context->cveIdentifier}",
            'repository' => $context->repository,
        ]);
    }
}
